[package]
name = "brim"
version = "2.2.1"
edition = "2021"

description = "An optimizing brain* interpreter."
authors = ["Kyllingene"]
repository = "https://github.com/kyllingene/brim"
license = "MIT"

keywords = ["cli", "command-line", "interpreter"]
categories = ["command-line-interface"]

[dependencies]
sarge = "3.0.1"

[features]
default = []
debug = []
