[package]
name = "brim"
version = "2.1.0"
edition = "2021"

license = "MIT"
description = "An optimizing brain* interpreter."
authors = ["Kyllingene"]
repository = "https://github.com/kyllingene/dirt"

[dependencies]
sarge = "3.0.1"

[features]
default = []
debug = []

